name: police_smart
description: تطبيق شرطة ذكي لجهاز الشرطة الفلسطينية
publish_to: 'none' # This is a private package.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.1
  device_info_plus: ^9.0.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
# Firebase Messaging
firebase_messaging: ^14.0.0
firebase_core: ^2.0.0
